version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: omc-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - omc-network

  frontend:
    build:
      context: ./src
    container_name: omc-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - omc-network

networks:
  omc-network:
    driver: bridge
